package.settings:
  type: config_object
  mapping:
    vendor:
      type: string
      label: 'Vendor'
    authman_instance_id:
      type: string
      label: 'Authman Instance ID'
    repositories:
      type: field.storage_settings.[%parent.type]
