package.settings:
  type: config_object
  mapping:
    vendor:
      type: string
      label: 'Vendor'
    instance_id:
      type: sequence
      label: 'Types'
      sequence:
        type: string
        label: 'Types'
